language: cpp
dist: bionic
compiler:
- gcc
os:
- linux
env:
  - DEBIAN_FRONTEND=noninteractive
before_install:
  - apt update
  - apt install scons build-essential libboost-all-dev
script:
- scons check
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#loonycyborg
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
