from SCons.Builder import Builder

env = Environment()

def e(target, source, env):
    print target
    print source
    print env
    return (target, source)

builder = Builder(
    action = { ".blah" : "echo blah_builder targets: $TARGETS sources: $SOURCES" },
    target_factory = env.File,
    prefix = "blah_",
    suffix = "blah",
    src_suffix = "blah",
    emitter = e,
    ensure_suffix = True)

multi_builder = Builder(
	action = "echo multi_builder targets: $TARGETS sources: $SOURCES",
	multi = True
	)

env.Append(BUILDERS = { "Blah" : builder , "Multi" : multi_builder })

env.Command("qux.blah", "SConstruct", "echo targets: $TARGETS  sources: $SOURCES")
env.AddPreAction("qux.blah", "echo PreAction $TARGET")
env.AddPostAction("qux.blah", "echo PostAction $TARGET")
blah = env.Blah("foo.bar", "qux")
env.Command("SConstruct.blah", "SConstruct", "echo targets: $TARGETS sources: $SOURCES")
print env.Blah("SConstruct")
baz = env.Multi(Alias("baz"), blah)
env.Multi(Alias("baz"), "blah_SConstruct.blah")
AlwaysBuild(baz)
env.Default(Alias("baz"))
