name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: sudo apt-get install -y scons pybind11-dev libboost-graph-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libboost-test-dev libsqlite3-dev
      - run: scons
      - run: scons check
      - run: ./scons++
